const errorCode = {
  501: "user is not authorized to perform this action",
  502: "Not allowed by CORS",
  503: "Url not found",
  504: "password must contain digit",
  505: "email_id is required",
  506: "please enter correct email_id",
  507: "Otp is requred!",
  508: "Please Resend the OTP",
  509: "Please enter currect OTP",
  510: "email is already exist",
  511: "email doesn't exist",
  512: "please enter correct password",
  513: "Please enter any one data",
  514: "Need to enter any one secrect key",
  515: "User type is required",
  516: "Refresh token is required",
  517: "Internal server error",
  518: "Not Available",
  519: "User_name required",
  520: "User name not found",
  521: "Name required",
  522: "Price required",
  523: "Already present in database",
  524: "Address required",
  525: "Phone required",
  526: "CategoryId required",
  527: "Count required",
  528: "please enter correct order_id",
  529: "please enter status",
};
const successCode = {
  201: "Data return seccessfully",
  202: "OTP Sent seccessfully",
  203: "Available",
  204: "Successfully Saved",
  205: "Successfully Created",
  206: "Successfully deleted",
};

module.exports = { errorCode, successCode };
